export const DATABASE_CONSTANTS = {
  DEFAULT_PORT: 5432,
  DEFAULT_POOL_SIZE: 10,
  DEFAULT_IDLE_TIMEOUT_MS: 30000,
  DEFAULT_CONNECTION_TIMEOUT_MS: 5000,
  SLOW_QUERY_THRESHOLD_MS: 1000,
  MAX_RETRY_ATTEMPTS: 3,
  RETRY_BASE_DELAY_MS: 100,
  MAX_RETRY_DELAY_MS: 5000,
} as const;
