export const WORKER_CONSTANTS = {
  POLL_ERROR_RETRY_DELAY_MS: 5000,
  SQS_MAX_MESSAGES_PER_POLL: 10,
  SQS_WAIT_TIME_SECONDS: 20,
  SQS_VISIBILITY_TIMEOUT_SECONDS: 60,
  SQS_EXTENDED_VISIBILITY_TIMEOUT_SECONDS: 300,
  SQS_DEFER_BASE_SECONDS: 15,
  SQS_DEFER_MAX_SECONDS: 120,
  MAX_RECEIVE_COUNT_THRESHOLD: 3,
} as const;
